#FROM jupyter/base-notebook
#FROM jupyter/datascience-notebook
FROM ubuntu:18.04

ENV GID 1000
ENV UID 1000
ENV GROUP buff
ENV USER buff

#USER root

RUN groupadd -g $GID $GROUP && useradd -m -u $UID -g $GID $USER

#ADD [--chown=$USER:$GROUP] . /home/$USER
WORKDIR /home/$USER

#RUN chown -R $USER:$GROUP /home/$USER
RUN chown -R buff:buff /home/buff
RUN apt update && \
    apt install -y python3 python3-pip
RUN pip3 install notebook #&& \
#    jupyter notebook --ip=0.0.0.0  --port=8888 --allow-root
RUN pip3 install python-edgar

USER $USER

ENTRYPOINT jupyter notebook --ip 0.0.0.0  --port 8888 --allow-root
